In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import openpyxl

In [5]:
df = pd.read_excel('Macro_econ_aggregates.xlsx')

In [6]:
df.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
27,NaN,Notes : 1. Data for 2024-25 are First Revised ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,2. Data for 2025-26 are Provisional Estimates.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,3. Population figures relate to mid-financial ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Also see Notes on Tables.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Source : National Statistics Office (NSO).,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,TABLE 1 : MACRO-ECONOMIC AGGREGATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,(At Current Prices),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,(Amount in ₹ Crore),NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Item/Year,2020-21,2021-22,2022-23,2022-23,2023-24,2024-25,2025-26
4,NaN,1,2,3,4,5,6,7,8

In [9]:
df.shape

(32, 9)

In [10]:
df.info

<bound method DataFrame.info of     Unnamed: 0                                         Unnamed: 1  \
0          NaN                TABLE 1 : MACRO-ECONOMIC AGGREGATES
1          NaN                                (At Current Prices)
2          NaN                                (Amount in ₹ Crore)
3          NaN                                          Item/Year
4          NaN                                                  1
5          NaN                                                NaN
6          NaN                              Population (in Lakhs)
7          NaN                                GVA at Basic Prices
8          NaN                              Net Taxes on Products
9          NaN                             Gross Domestic Product
10         NaN                       Consumption of Fixed Capital
11         NaN                               Net Domestic Product
12         NaN           Primary Income Receivable from ROW (net)
13         NaN                              Gross National Income
14         NaN                                Net National Income
15         NaN             Other Current Transfers (net) from ROW
16         NaN                   Gross National Disposable Income
17         NaN                     Net National Disposable Income
18         NaN                                       Gross Saving
19         NaN                                        Net Savings
20         NaN                            Gross Capital Formation
21         NaN                              Net Capital Formation
22         NaN                                 Per Capita GDP (₹)
23         NaN                                 Per Capita GNI (₹)
24         NaN                                 Per Capita NNI (₹)
25         NaN                                Per Capita GNDI (₹)
26         NaN                                Per Capita PFCE (₹)
27         NaN  Notes : 1. Data for 2024-25 are First Revised ...
28         NaN     2. Data for 2025-26 are Provisional Estimates.
29         NaN  3. Population figures relate to mid-financial ...
30         NaN                          Also see Notes on Tables.
31         NaN         Source : National Statistics Office (NSO).

              Unnamed: 2 Unnamed: 3 Unnamed: 4            Unnamed: 5  \
0                    NaN        NaN        NaN                   NaN
1                    NaN        NaN        NaN                   NaN
2                    NaN        NaN        NaN                   NaN
3                2020-21    2021-22    2022-23               2022-23
4                      2          3          4                     5
5   (Base Year: 2011-12)        NaN        NaN  (Base Year: 2022-23)
6                  13554      13686      13829                 13829
7               18210997   21635584   24646698              23763761
8                1643099    1961815    2243775               2353866
9               19854096   23597399   26890473              26117627
10               2340587    2666804    3129241               3682266
11              17513509   20930595   23761232              22435361
12               -266687    -277808    -370307               -370307
13              19587409   23319590   26520166              25747320
14              17246821   20652786   23390925              22065054
15                552188     605444     819212                819212
16              20139597   23925034   27339378              26566532
17              17799010   21258230   24210137              22884266
18               5786929    7363103    8244048               7772917
19               3446342    4696299    5114808               4090651
20               5597593    7648091    8771573               8987545
21               3257005    4981287    5642332               5305278
22                146480     172422     194451                188862
23                144512     170392     191773                186184
24                127244     150906     169145                159557
25                148586     174816     197697                192108
26                 89496     105092     119516                107910
27                   NaN        NaN        NaN                   NaN
28                   NaN        NaN        NaN                   NaN
29                   NaN        NaN        NaN                   NaN
30                   NaN        NaN        NaN                   NaN
31                   NaN        NaN        NaN                   NaN

   Unnamed: 6 Unnamed: 7 Unnamed: 8
0         NaN        NaN        NaN
1         NaN        NaN        NaN
2         NaN        NaN        NaN
3     2023-24    2024-25    2025-26
4           6          7          8
5         NaN        NaN        NaN
6       13955      14081      14206
7    26316103   28854467   31486840
8     2667807    2952841    3148798
9    28983909   31807309   34635638
10    3946581    4254383          -
11   25037329   27552926   29993131
12    -411996    -409303          -
13   28571913   31398006   34204634
14   24625333   27143623   29562127
15     883215    1053958          -
16   29455128   32451963   35401638
17   25508548   28197581   30759131
18    9517450   11113324          -
19    5570870    6858941          -
20   10000806   10924508          -
21    6054226    6670126          -
22     207699     225896     243803
23     204746     222989     240769
24     176465     192774     208090
25     211076     230474     249195
26     117356     127627     138324
27        NaN        NaN        NaN
28        NaN        NaN        NaN
29        NaN        NaN        NaN
30        NaN        NaN        NaN
31        NaN        NaN        NaN  >

In [14]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8'],
      dtype='str')

In [15]:
df.isnull().sum()

Unnamed: 0    32
Unnamed: 1     1
Unnamed: 2     8
Unnamed: 3     9
Unnamed: 4     9
Unnamed: 5     8
Unnamed: 6     9
Unnamed: 7     9
Unnamed: 8     9
dtype: int64

In [16]:
df.dtypes

Unnamed: 0    float64
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
Unnamed: 8     object
dtype: object

In [17]:
df = df.drop(columns=['Unnamed: 0'])

In [18]:
df.iloc[7:28]

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
7,GVA at Basic Prices,18210997,21635584,24646698,23763761,26316103,28854467,31486840
8,Net Taxes on Products,1643099,1961815,2243775,2353866,2667807,2952841,3148798
9,Gross Domestic Product,19854096,23597399,26890473,26117627,28983909,31807309,34635638
10,Consumption of Fixed Capital,2340587,2666804,3129241,3682266,3946581,4254383,-
11,Net Domestic Product,17513509,20930595,23761232,22435361,25037329,27552926,29993131
12,Primary Income Receivable from ROW (net),-266687,-277808,-370307,-370307,-411996,-409303,-
13,Gross National Income,19587409,23319590,26520166,25747320,28571913,31398006,34204634
14,Net National Income,17246821,20652786,23390925,22065054,24625333,27143623,29562127
15,Other Current Transfers (net) from ROW,552188,605444,819212,819212,883215,1053958,-
16,Gross National Disposable Income,20139597,23925034,27339378,26566532,29455128,32451963,35401638
17,Net National Disposable Income,17799010,21258230,24210137,22884266,25508548,28197581,30759131
18,Gross Saving,5786929,7363103,8244048,7772917,9517450,11113324,-
19,Net Savings,3446342,4696299,5114808,4090651,5570870,6858941,-
20,Gross Capital Formation,5597593,7648091,8771573,8987545,10000806,10924508,-
21,Net Capital Formation,3257005,4981287,5642332,5305278,6054226,6670126,-
22,Per Capita GDP (₹),146480,172422,194451,188862,207699,225896,243803
23,Per Capita GNI (₹),144512,170392,191773,186184,204746,222989,240769
24,Per Capita NNI (₹),127244,150906,169145,159557,176465,192774,208090
25,Per Capita GNDI (₹),148586,174816,197697,192108,211076,230474,249195
26,Per Capita PFCE (₹),89496,105092,119516,107910,117356,127627,138324
27,Notes : 1. Data for 2024-25 are First Revised ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN